language: minimal
sudo: required
services:
  - docker
env:
  global:
  - secure: WyeusVDQyOGk9xNrcdDN7zg2UaZApQn/P30QUf/DfjosF3saVfSWP8O4LjBJkEOY7b+R6oMmPuS3Tj0DrIcjfcJBijsuCvKVIlpm479ndrGJyGTA20/y2mTwy2Kl6jAj2HteMLSO54F2PtBtDqH6HejqX/NtjBDRQ+0/9zPB7N5kRNE8vsoZn34q6Pgwiy/YkrULpTonztTc3ZCtTVyhx9iD+UowXi9473OfqvhBXUV3JnvXqx7vXBjJ8tzbuNMpeATkMgA5v7bPfMSXezpt7gQzjgPv2gORENy0ImmfGJP/83Dpf1fkdyZMWKRWujwucckpkCapI2icIzaJEaKUhJGHDk/DrxeL6ZURgIMo+7RpoJa+OWJ200M0+mcxBKDplzqlrpi6GDAhi7HIECJGpWyW7v4t/qTEFSIaNvG7R92W/ocCpcXsYyOfRPbEhRCBQRNSQje3nDXByMdjo5xWNFKyXzj/2cHv5ytVgzyKCWrGe1s/onpDK1YiXWr6ytEPQ33mIa78pXng/1G7DZZJQkfh94TGVE98j7Zljhm1RNcJxhR4/tp3l7n/+sKlGAAUAlL86QUeuoQgy6v0W+3BJ3IxDbG3Xc/D+1QI2oU1OHnFyI1892rbPGHTxUOBAM810EuNi0qropizz1tPWleAJ3JAYzD8dDhALAfmN+ucrJo=
  - secure: TKcxMgqM34h2WlGoJRGXVyPfwjoos6wIXDhbx01U6IrBLZmb3Z5MPaA0tYbpJXsgM/3Dk5EGLOt+Fsa9tqM4msumspDN5zUQgeqym1BpdJX8GuEcaBPnycLdwIJY1H1r2YBMKWD/bhei0pDKfMK//H60mVfSNsbpseItGG88gzqRYeTwPkYPDqr9qhOXtx8vLyIqmiwL1jvV3ImIxqBINjZNuUW2QWslKnWSrTI8gx8y0ydvrcWnRFpY429qcmkLCHZh6kzQzeTM/MMjxx968lbVNxLNjSesAVaFPyEn8Z8aE1pR8clNy7Tqjor+GRPI/5NcuQrG1VV0JkSCIzF9+f2mCeUAd976rXnUl7XzBWOxm19MDXU35MSDTQSnTmH6CpEh4RQ8U79XVzdRAF5Lf7Sl+8U9wM3KUrWqUhNN1qtAuekJWf8J6DfR0cDL1th8j63x3Bhkewzgca5MI7zACClr+KIp8zH157DISLUeNUJpk7uBsNTOisWB5iJuXqxvAff8AbRkFCoGCag9D6DCokX9OoflRo4xvfxm/O1smmDpoonjKgz7L/+SCpIFxYjcyouYspViSAnnCxVaBfk2rha5NP6Br6sPeGvBP+p4BBoIG9/pFGP/N3vRrz2sM/FBs7GdQ6BSnuxgSILXeAGm3pOnDDvveBIXOj5yJFIVXAc=
script: make
deploy:
  - provider: script
    script: make
    on:
      branch: master
  - provider: script
    script: make build login push
    on:
      branch: master
      tags: true